import { NextResponse } from "next/server";

export async function GET() {
  const tools = [
    {
      name: "search_catalog",
      description: "Search the merchant's catalog for products using natural language. Use this to find product IDs, check stock, and get pricing in paise. Note: This endpoint is rate-limited to 15 requests per minute. If you receive a 429 Too Many Requests response, read the X-RateLimit-Reset header and wait before retrying.",
      parameters: {
        type: "object",
        properties: {
          query: {
            type: "string",
            description: "The semantic search query (e.g., 'ergonomic chair for back pain').",
          },
          maxPrice: {
            type: "number",
            description: "Optional maximum price filter in paise (₹1 = 100 paise).",
          },
          limit: {
            type: "number",
            description: "Number of results to return (default is 5, max is 20).",
          }
        },
        required: ["query"],
      },
    },
    {
      name: "execute_checkout",
      description: "Generate a secure Razorpay order for a specific product. Requires an active agent session token and sufficient budget.",
      parameters: {
        type: "object",
        properties: {
          productId: {
            type: "string",
            description: "The UUID of the product to purchase.",
          },
          quantity: {
            type: "number",
            description: "The number of items to purchase.",
          },
          idempotencyKey: {
            type: "string",
            description: "A unique UUIDv4 string generated by the buyer to prevent accidental double-charging during network retries.",
          }
        },
        required: ["productId", "quantity", "idempotencyKey"],
      },
    },
    {
      name: "list_catalog",
      description: "Retrieve a paginated list of all products in the merchant's catalog. Use this to view all available inventory or sort items to find low stock.",
      parameters: {
        type: "object",
        properties: {
          page: {
            type: "number",
            description: "The page number to retrieve (default is 1).",
          },
          limit: {
            type: "number",
            description: "The number of items per page (default is 10, max is 100).",
          },
          sort: {
            type: "string",
            description: "The sorting parameter. Use 'name' for alphabetical order, or 'stock' to sort by available inventory from lowest to highest.",
            enum: ["name", "stock"]
          }
        },
        required: [],
      },
    }
  ];

  return NextResponse.json({
    status: "success",
    merchant: "Agent-Buyer API Gateway",
    supported_protocols: ["agent-to-agent"],
    tools: tools,
  });
}